name: coordtransform
description: a coord transform tool, Provide BD09、GCJ02、WGS84 coordinate system mutual transform.
version: 1.0.1
homepage: https://github.com/fluttercandies/coordtransform

environment:
  sdk: ">=2.12.0 <3.0.0"